query ($id: Int!) {
	Character(id: $id) {
		age
		bloodType
		name {
			userPreferred
			alternative
			alternativeSpoiler
		}
		dateOfBirth {
			day
			month
			year
		}
		favourites
		image {
			large
		}
		isFavourite
		description
		siteUrl
		gender

		media {
			edges {
				id
				characterRole
				node {
					id
					title {
						english
						romaji
					}
					coverImage {
						large
					}
				}
			}
		}
	}
}
