query ($type: MediaType!, $userId: Int!) {
	MediaListCollection(type: $type, userId: $userId) {
		lists {
			name
			entries {
				id
				media {
					id
					episodes
					status
					nextAiringEpisode {
						episode
						airingAt
					}
					coverImage {
						large
						color
					}
					title {
						userPreferred
					}
					mediaListEntry {
						status
						progress
						repeat
					}
				}
			}
		}
	}
}
