query ($id: Int!) {
	Media(id: $id) {
		id
		bannerImage
		description
		episodes
		status
		genres
		volumes
		chapters
		coverImage {
			large
			color
		}
		title {
			userPreferred
		}
		nextAiringEpisode {
			episode
			airingAt
		}
		characters {
			edges {
				role
				node {
					id
					image {
						medium
					}
					name {
						userPreferred
						native
						full
					}
				}
				voiceActors {
					languageV2
					id
					name {
						userPreferred
						native
						full
					}
					image {
						medium
					}
				}
			}
		}
		recommendations {
			nodes {
				mediaRecommendation {
					id
					episodes
					status
					nextAiringEpisode {
						episode
						airingAt
					}
					coverImage {
						large
					}
					title {
						userPreferred
					}
					mediaListEntry {
						status
						progress
						repeat
					}
				}
			}
		}
	}
}
