query (
	$search: String
	$isAdult: Boolean
	$averageScoreUpperRange: Int
	$averageScoreBottomRange: Int
	$chaptersUpperRange: Int
	$chaptersBottomRange: Int
	$volumesUpperRange: Int
	$volumesBottomRange: Int
	$episodesUpperRange: Int
	$episodesBottomRange: Int
	$countryOfOrigin: CountryCode
	$startDateUpperRange: FuzzyDateInt
	$startDateBottomRange: FuzzyDateInt
	$endDateUpperRange: FuzzyDateInt
	$endDateBottomRange: FuzzyDateInt
	$format: MediaFormat
	$status: MediaStatus
	$includeAnime: Boolean!
	$includeManga: Boolean!
	$includeCharacters: Boolean!
	$includeStaff: Boolean!
	$includeStudios: Boolean!
	$includeUsers: Boolean!
	$animePage: Int
	$mangaPage: Int
	$charactersPage: Int
	$staffPage: Int
	$studiosPage: Int
	$usersPage: Int
) {
	anime: Page(perPage: 8, page: $animePage) @include(if: $includeAnime) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: media(
			type: ANIME
			isAdult: $isAdult
			search: $search
			averageScore_greater: $averageScoreBottomRange
			averageScore_lesser: $averageScoreUpperRange
			episodes_greater: $episodesBottomRange
			episodes_lesser: $episodesUpperRange
			countryOfOrigin: $countryOfOrigin
			startDate_greater: $startDateBottomRange
			startDate_lesser: $startDateUpperRange
			endDate_greater: $endDateBottomRange
			endDate_lesser: $endDateUpperRange
			format: $format
			status: $status
		) {
			id
			format
			title {
				userPreferred
			}
			coverImage {
				medium
			}
			startDate {
				month
				year
			}
		}
	}
	manga: Page(perPage: 8, page: $mangaPage) @include(if: $includeManga) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: media(
			type: MANGA
			isAdult: $isAdult
			search: $search
			averageScore_greater: $averageScoreBottomRange
			averageScore_lesser: $averageScoreUpperRange
			chapters_greater: $chaptersBottomRange
			chapters_lesser: $chaptersUpperRange
			volumes_greater: $volumesBottomRange
			volumes_lesser: $volumesUpperRange
			countryOfOrigin: $countryOfOrigin
			startDate_greater: $startDateBottomRange
			startDate_lesser: $startDateUpperRange
			endDate_greater: $endDateBottomRange
			endDate_lesser: $endDateUpperRange
			format: $format
			status: $status
		) {
			id
			format
			title {
				userPreferred
			}
			coverImage {
				medium
			}
			startDate {
				month
				year
			}
		}
	}
	characters: Page(perPage: 8, page: $charactersPage) @include(if: $includeCharacters) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: characters(search: $search) {
			id
			name {
				userPreferred
			}
			image {
				medium
			}
		}
	}
	staff: Page(perPage: 8, page: $staffPage) @include(if: $includeStaff) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: staff(search: $search) {
			id
			primaryOccupations
			name {
				userPreferred
			}
			image {
				medium
			}
		}
	}
	studios: Page(perPage: 13, page: $studiosPage) @include(if: $includeStudios) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: studios(search: $search) {
			id
			name
		}
	}
	users: Page(perPage: 8, page: $usersPage) @include(if: $includeUsers) {
		pageInfo {
			total
			currentPage
			lastPage
		}
		results: users(search: $search) {
			id
			name
			avatar {
				medium
			}
		}
	}
}
